version: "3.7"
services:
    #ftp-docker:
    #  build: ftp-docker/
    #  ports: 
    #    - 8021:80

    nginx:
      container_name: nginx
      build:
        context: ./nginx/
        dockerfile: Dockerfile-dev
      ports:
        - 80:80
      #links:
      #  - switter-front
      #  - switter-back
    switter-front:
      container_name: switter-front
      build:
        context: ./switter-front/
        dockerfile: Dockerfile-dev
      volumes:
      - "./src/switter-front/:/var/www/switter-front/"
      ports:
        - 8181:8080
    switter-back:
      container_name: switter-back
      #build: ./switter-back/
      build: 
        context: ./
        dockerfile: ./switter-back/Dockerfile
      ports:
        - 8192:8080
    db:
      container_name: postgres
      build: ./postgres/
      #image: postgres
      ports:
        - 5432:5432
      volumes:
        - pg12-data:/var/lib/postgresql/
        #- type: bind
        ##  source: ./postgres/data/
        #  target: /var/lib/postgresql/pgdata:z
        #- "./postgres/data/:/var/lib/postgresql/"
volumes:
  "pg12-data":