version: "3.7"
volumes:
  "pg12-data":
#networks:
#  postgres-network:
#    driver: bridge
#  service-network:
#    driver: bridge
services:
    #ftp-docker:
    #  build: ftp-docker/
    #  ports: 
    #    - 8021:80

    nginx:
      container_name: nginx
      build:
        context: ./switter-front/
        dockerfile: Dockerfile
      ports:
        - 80:80
      volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- ./nginx.conf:/etc/nginx/nginx.conf
      environment:
        - NGINX_HOST=switter.dev
      links:
        - switter-back
    switter-back:
      container_name: switter-back
      build: 
        context: ./switter-back/
        dockerfile: ./Dockerfile
      ports:
        - 8192:8080
      links:
        - postgres
    postgres:
      container_name: postgres
      build: ./postgres/
      #image: postgres
      ports:
        - 5432:5432
      volumes:
        - pg12-data:/var/lib/postgresql/
