version: "3.2"
volumes:
  "pg12-data":
#networks:
#  postgres-network:
#    driver: bridge
#  service-network:
#    driver: bridge
services:
    #ftp-docker:
    #  build: ftp-docker/
    #  ports: 
    #    - 8021:80
    nginx-prod:
      container_name: nginx-prod
      build:
        context: ./switter-front/
        dockerfile: Dockerfile
      ports:
        - 80:80
      volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- ./nginx.conf:/etc/nginx/nginx.conf
      environment:
        - NGINX_HOST=switter.pro
      links:
        - switter-back
        - switter-auth
      env_file:
        - ./var.env
    switter-back:
      container_name: switter-back
      build: 
        context: ./switter-back/
        dockerfile: ./Dockerfile
      ports:
        - 8192:8080
      links:
        - postgres
      env_file:
        - ./var.env
    switter-auth:
      container_name: switter-auth
      build:
        context: ./switter-auth/
        dockerfile: Dockerfile-prod
      ports:
        - 9000:9000
      volumes:
        - ./switter-auth/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      env_file:
        - ./var.env
    postgres:
      container_name: postgres
      build: ./postgres/
      #image: postgres
      ports:
        - 5432:5432
      volumes:
        - pg12-data:/var/lib/postgresql/
