# build stage
FROM node:lts-alpine as build-stage
WORKDIR /var/www/switter-front/
COPY ./src/switter-front/package.json .
COPY ./src/switter-front/package-lock.json .
COPY ./src/switter-front/public/ .
RUN mkdir ./src
COPY ./src/switter-front/babel.config.js .
COPY ./src/switter-front/vue.config.js .
RUN npm cache verify
RUN npm install
RUN npm install -g @vue/cli @vue/cli-service
RUN npm install --save vue-axios axios

EXPOSE 8080
CMD ["npm", "run", "serve"]